name: finanza_auto
description: Módulo Carro do Finanza com dados locais reais.
publish_to: 'none'
version: 1.1.2+4

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: DM Sans
      fonts:
        - asset: assets/fonts/dm_sans_variable.ttf
    - family: Syne
      fonts:
        - asset: assets/fonts/syne_variable.ttf
  assets:
    - assets/finanza-auto-backup.json
